# Generated by Django 3.1.7 on 2021-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_historicalorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shop.Product'),
        ),
    ]
